# ProBot Stale (https://probot.github.io/apps/stale/)

# Number of days of inactivity before an issue becomes stale
daysUntilStale: 180

# Number of days of inactivity before a stale issue is closed
daysUntilClose: 14

# Issues with these labels will never be considered stale
exemptLabels:
  - accepted
  - blocked
  - bug
  - dependency
  - enhancement
  - 'help wanted'
  - question
  - security
  - meta

# Label to use when marking an issue as stale
staleLabel: stale

# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  Is this still relevant? If so, what is blocking it? Is there anything you can do to help move it forward?

# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false

# Limit to only `issues` or `pulls`
only: issues
